apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: key-1
#  namespace: aris
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: example               # name of the SecretStore (or kind specified)
  target:
    name: mongo-uri  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: mong-uri-test # name of the GCPSM secret key
      remoteRef:
        version: "latest"
        key: mong-uri
    - secretKey: redis-creds # name of the GCPSM secret key
      remoteRef:
        version: "1"
        key: redis-creds
---
