apiVersion: v1
kind: Secret
metadata:
  name: gcpsm-secret
  #  namespace: aris
  labels:
    type: gcpsm
type: Opaque
stringData:
  secret-access-credentials: |-
    {}
#    Secret here
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: example
#  namespace: aris
spec:
  provider:
    gcpsm:                                  # gcpsm provider
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret              # secret name containing SA key
            key: secret-access-credentials  # key name containing SA key
      projectID: mussia-infra
