[package]
name = "rust_actix_app"
version = "0.1.0"
edition = "2021"


[dependencies]
#mongo = { path = "../../../libs/rust/mongo" }
async-trait = { version = "0.1.73" }
actix-web = "4"
mongodb = "2.6.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.105", features = ["arbitrary_precision"] }
env_logger = "0.10.0"
log = "0.4"
futures = "0.3.28"
utoipa = { version = "3.3.0", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "3.1.4", features = ["actix-web"] }
validator = { version = "0.16.1", features = ["derive"] }
actix-cors = "0.6.4"
plurals = "0.4.0"
ts-rs = { version = "6.2.1", features = ["serde-compat"] }
serde_derive = "1.0.183"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
