[package]
name = "rust_actix_app"
version = "0.1.0"
edition = "2021"


[dependencies]
#mongo = { path = "../../../libs/rust/mongo" }
#mongo = { path = "../../../libs/rust/mongo" }
mongo = { workspace = true }
kube = { workspace = true }
k8s-openapi = { workspace = true }
async-trait = { version = "0.1.73" }
actix-web = { workspace = true }
actix-cors = { workspace = true }
mongodb = "2.6.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.106", features = ["arbitrary_precision"] }
env_logger = "0.10.0"
log = { workspace = true }
futures = { workspace = true }
utoipa = { version = "3.5.0", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "3.1.5", features = ["actix-web"] }
plurals = "0.4.0"
ts-rs = { version = "7.0.0", features = ["serde-compat"] }
serde_derive = "1.0.188"
validator = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc.workspace = true

[dev-dependencies]
rand.workspace = true
