
# docker_build(
#   "yurikrupnik/actix-app",
#   # "../../..",
#   ".",
#   target="rust",
# )

docker_build(
  "actix-app",
  "../../..",
  # ".",
  # dockerfile_contents="../../..",
  dockerfile="../../../Dockerfile.rust",
  build_args={"APP_NAME":"rust_actix_app"},
  target="rust",
  # only=["apps/rust/actix-app"],
)
# k8s_resource("actix-app1", port_forwards="5301:8080")

k8s_yaml(kustomize('k8s/base'))

k8s_resource("actix-app", port_forwards="5201:8080")
