
docker_build(
  "yurikrupnik/actix-app",
  "../../..",
  dockerfile="../../../Dockerfile.rust",
  build_args={"APP_NAME":"rust_actix_app"},
  target="rust",
)

k8s_resource("actix-app", port_forwards="5201:8080")
