[package]
name = "rust_clapper"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.4.3", features = ["derive"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
