[package]
name = "rust_clapper"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { workspace = true, features = ['derive'] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
