[package]
name = "rust_clapper"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { workspace = true }
#for-fun = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
