apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositesqls.multicloud.platformref.yurikrupnik.com
spec:
  claimNames:
    kind: Sql
    plural: sqls
  group: multicloud.platformref.yurikrupnik.com
  #           todo test it!
#  connectionSecretKeys:
#    - kubeconfig
#    - value
  #           todo test it!
#  defaultCompositionRef:
#    name: cluster-aws
  names:
    kind: CompositeSql
    plural: compositesqls
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                location:
                  type: string
                  description: Location where the instance should be created.
#                storageClass:
#                  type: string
#                  description: Storage Class of the bucket.
#                  default: STANDARD
#                  enum:
#                    - STANDARD
#                    - MULTI_REGIONAL
#                    - REGIONAL
#                    - NEARLINE
#                    - COLDLINE
#                    - ARCHIVE
#                labels:
#                  type: array
#                  description: Labels to apply to the bucket.
#                  items:
#                    type: object
#                    properties:
#                      key:
#                        type: string
#                        description: Label key.
#                      value:
#                        type: string
#                        description: Label value.
              required:
                - location

            status:
              type: object
              properties:
                url:
                  type: string
