apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-users-redis
  labels:
    app: node-users-redis
spec:
  replicas: 1
  template:
    metadata:
      name: node-users-redis
      labels:
        app: node-users-redis
    spec:
      serviceAccountName: node-users-redis
      containers:
        - name: node-users-redis
          image: yurikrupnik/node-users-redis:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  key: mongo-uri
                  name: mongo-uri
            - name: REDIS_HOST
              value: "redis-service.default.svc.cluster.local"
      restartPolicy: Always
  selector:
    matchLabels:
      app: node-users-redis
