#apiVersion: rbac.authorization.k8s.io/v1
#kind: Role
#metadata:
#  namespace: default
#  name: pod-reader-role
#rules:
#  - apiGroups: [""]
#    resources: ["pods"]
#    verbs: ["get", "list"]  # Adjust the verbs as needed
#
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  name: pod-reader-role-binding
#  namespace: default
#subjects:
#  - kind: ServiceAccount
#    name: master-operator
#    namespace: default
#roleRef:
#  kind: Role
#  name: pod-reader-role
#  apiGroup: rbac.authorization.k8s.io

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-manager
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - clux.dev   # Update this to the actual API group of your CRD
    resources:
      - foos       # Update this to the resource name of your CRD
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-manager-binding
subjects:
  - kind: ServiceAccount
    name: master-operator
    namespace: default  # Change this to the correct namespace if needed
roleRef:
  kind: ClusterRole
  name: crd-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: clux.dev/v1
kind: Foo
metadata:
  name: yur
spec:
  info: omg is it my info
  name: shalom
  replicas: 4