apiVersion: v1
kind: Service
metadata:
  name: master-operator-service
  labels:
    run: master-operator-service
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: master-operator
