
[workspace]
members = [
	'libs/rust/grpc',
	'libs/rust/mongo',
	'apps/rust/mongo-api',
	'apps/rust/master_operator',
	'apps/rust/actix_app',
	'apps/rust/clapper',
	'apps/rust/actix_htmx',
	'apps/rust/axum_htmx',
	'apps/rust/axum_app',
	'apps/rust/test_app',
	'libs/rust/servers_shared',
	'libs/rust/napi_shared',
]

[profile.release]
lto = true
strip = true
opt-level = 3
