
[workspace]
members = [
	'libs/rust/grpc',
	'libs/rust/mongo',
	'apps/rust/mongo-api',
	'apps/rust/master_operator',
	'apps/rust/actix_app',
	'apps/rust/clapper',
	'libs/rust/stam',
	'libs/rust/kubernetes_operator_api',
	'apps/rust/users_operator',
	'apps/rust/metacontroller_operator',
	'libs/rust/local_cluster',
	'apps/rust/job_operator_sample',
	'libs/rust/proc_ts',
	'libs/rust/ts_shared',
	'libs/rust/for_fun',
	'apps/rust/cli_app',
]

[workspace.dependencies]
clap = { version = '4.4', features = ['derive'] }
cc = '1.0'
rand = '0.8'
regex = { version = '1.6', default-features = false, features = ['std'] }
actix-web = '4'
actix-cors = '0.6.4'
mongo = { path = 'libs/rust/mongo' }
#for-fun = { path = 'libs/rust/for_fun' }
anyhow = '1.0'
backoff = '0.4'
futures = '0.3'
k8s-openapi = { version = '0.20', features = ['v1_28'] }
kube = { version = '0.86', features = ['derive', 'runtime'] }
log = '0.4.20'
schemars = '0.8.13'
serde = { version = '1.0', features = ['derive'] }
serde_json = '1.0'
serde_yaml = '0.9'
thiserror = '1.0'
tokio = { version = '1.32', features = ['macros', 'signal', 'rt-multi-thread'] }
tracing = '0.1'
tracing-subscriber = '0.3'
validator = { version = '0.16', features = ['derive'] }
#actix-web = "4.4.0"

[profile.release]
lto = true
strip = true
opt-level = 3
