
[workspace]
members = [
	'libs/rust/grpc',
	'libs/rust/mongo',
	'apps/rust/mongo-api',
	'apps/rust/master_operator',
	'apps/rust/actix_app',
	'apps/rust/clapper',
	'libs/rust/stam',
	'libs/rust/kubernetes_operator_api',
	'apps/rust/users_operator',
	'apps/rust/metacontroller_operator',
]

[profile.release]
lto = true
strip = true
opt-level = 3
