version: "3.8"
services:
  db:
    image: "mongo"
    ports:
      - "27017:27017"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

#  front-app:
#    volumes:
#      - ./nginx.conf:/etc/nginx/default.conf
#    build:
#      context: "."
#      dockerfile: Dockerfile
#      target: "nginx"
#      args:
#        - DIST_PATH=dist/apps/frontend/solid-app
#    container_name: front-app
#    environment:
#      - VITE_HOST=http://localhost:8082
##      - UPSTREAM_HOST=nest-app
##      - UPSTREAM_PORT="8082"
##      - UPSTREAM_NAME=backend
#    ports:
#      - "8090:80"
#  nest-app:
#    volumes:
#      - ./_proto/users.proto:/app/assets/users.proto
#    build:
#      context: "."
#      dockerfile: Dockerfile
#      target: "node"
#      args:
#        - DIST_PATH=dist/apps/node/nest-app
#        - PORT=8080
#    container_name: nest-app
#    environment:
#      - MONGO_URI=mongodb://db/compose
#      - REDIS_HOST=redis
#      - NODE_ENV=production
#      - GRPC_HOST=grpc-app
#    ports:
#      - "8082:8080"
#    depends_on:
#      - db
#      - redis
#  redis-app:
#    build:
#      context: "."
#      dockerfile: Dockerfile
#      target: "node"
#      args:
#        - DIST_PATH=dist/apps/node/node-users-redis
#        - PORT=8080
#    container_name: redis-app
#    environment:
#      - MONGO_URI=mongodb://db/compose
#      - REDIS_HOST=redis
#      - NODE_ENV=production
#    depends_on:
#      - db
#      - redis
#  grpc-app:
#    volumes:
#      - ./_proto/users.proto:/app/assets/users.proto
#    build:
#      context: "."
#      dockerfile: Dockerfile
#      target: "node"
#      args:
#        - DIST_PATH=dist/apps/node/node-users-grpc
#        - PORT=8080
#    container_name: grpc-app
#    environment:
#      - MONGO_URI=mongodb://db/compose
#      - REDIS_HOST=redis
#      - NODE_ENV=production
#      - GRPC_HOST=grpc-app
#    depends_on:
#      - db
#      - redis
