apiVersion: v1
kind: Service
metadata:
  name: ntex-app-service
  annotations:
    "prometheus.io/scrape": "true"
  labels:
    run: ntex-app-service
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ntex-app
