apiVersion: apps/v1
kind: Deployment
metadata:
  name: salvo-app
  labels:
    app: salvo-app
spec:
  replicas: 1
  template:
    metadata:
      name: salvo-app
      labels:
        app: salvo-app
    spec:
      serviceAccountName: salvo-app
      restartPolicy: Always
      containers:
        - name: salvo-app
          image: yurikrupnik/salvo-app:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  key: mongo-uri
                  name: mongo-uri
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: postgres-uri
                  name: postgres
  selector:
    matchLabels:
      app: salvo-app
