apiVersion: apps/v1
kind: Deployment
metadata:
  name: deno-nest
  labels:
    app: deno-nest
spec:
  replicas: 1
  template:
    metadata:
      name: deno-nest
      labels:
        app: deno-nest
    spec:
      serviceAccountName: deno-nest
      restartPolicy: Always
      containers:
        - name: deno-nest
          image: yurikrupnik/deno-nest:main
#          image: europe-central2-docker.pkg.dev/mussia-infra/container-repository/actix-app:main
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  key: mongo-uri
                  name: mongo-uri
  selector:
    matchLabels:
      app: deno-nest
#---
#apiVersion: monitoring.coreos.com/v1
#kind: PodMonitor
#metadata:
#  name: deno-nest
##  labels:
##    team: backend
#spec:
#  selector:
#    matchLabels:
#      app: deno-nest
#  podMetricsEndpoints:
#    - port: web

#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: prometheus
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  name: prometheus
#rules:
#  - apiGroups: [""]
#    resources:
#      - nodes
#      - nodes/metrics
#      - services
#      - endpoints
#      - pods
#    verbs: ["get", "list", "watch"]
#  - apiGroups: [""]
#    resources:
#      - configmaps
#    verbs: ["get"]
#  - apiGroups:
#      - networking.k8s.io
#    resources:
#      - ingresses
#    verbs: ["get", "list", "watch"]
#  - nonResourceURLs: ["/metrics"]
#    verbs: ["get"]
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: prometheus
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: prometheus
#subjects:
#  - kind: ServiceAccount
#    name: prometheus
#    namespace: default
