apiVersion: v1
kind: Service
metadata:
  name: deno-nest-app-service
  labels:
    run: deno-nest-app-service
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: deno-nest-app
