[package]
name = "rust_axum_app"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.32", features = ["full"] }
axum = { version = "0.6" }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
