docker_build(
  "yurikrupnik/axum-app",
  "../../..",
  dockerfile="../../../rust.Dockerfile",
  build_args={"APP_NAME":"rust_axum_app"},
  target="rust",
)

k8s_resource("axum-app", port_forwards="5221:8080")
