apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: Schema
metadata:
  name: kustomize-example-app1-example-schema-c874d161
spec:
  forProvider:
    definition: '{"type":"record","name":"Avro","fields":[{"name":"StringField","type":"string"},{"name":"FloatField","type":"float"},{"name":"BooleanField","type":"boolean"}]}'
    type: AVRO
---
apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: Topic
metadata:
  name: kustomize-example-app1-example-topic-c8790a4a
spec:
  forProvider:
    schemaSettings:
      - encoding: AVRO
        schema: '{"type":"record","name":"Avro","fields":[{"name":"StringField","type":"string"},{"name":"FloatField","type":"float"},{"name":"BooleanField","type":"boolean"}]}'
