apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp.compositeregistrys.multicloud.platformref.yurikrupnik.com
  labels:
    provider: GCP
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: multicloud.platformref.yurikrupnik.com/v1alpha1
    kind: CompositeRegistry
  resources:
    - base:
        apiVersion: multicloud.platformref.yurikrupnik.com/v1alpha1
        kind: Storage
        metadata:
          name: storage-aws
        spec:
          location: us-west-2
          compositionSelector:
            matchLabels:
              provider: aws
#      patches:
#        - fromFieldPath: spec.forProvider.region
#          toFieldPath: spec.forProvider.location
#        - fromFieldPath: spec.id
#          toFieldPath: metadata.labels[networks.multicloud.platformref.yurikrupnik.com/network-id]

    - base:
        apiVersion: multicloud.platformref.yurikrupnik.com/v1alpha1
        kind: Network
        metadata:
          name: network-gcp
        spec:
          id: multik8s-network-gcp
          clusterRef:
            id: multik8s-cluster-gcp
          compositionSelector:
            matchLabels:
              provider: GCP
