apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp.compositeprojects.multicloud.platformref.yurikrupnik.com
  labels:
    provider: GCP
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: multicloud.platformref.yurikrupnik.com/v1alpha1
    kind: CompositeProject
  resources:
#    - name: Cache
#      base:
#        apiVersion: multicloud.platformref.yurikrupnik.com/v1alpha1
#        kind: Redis
#        metadata:
#          name: redis-gcp-instance
#          namespace: crossplane-system
#        spec:
#          location: me-west1
#          compositionSelector:
#            matchLabels:
#              provider: GCP
#    - name: Database
#      base:
#        apiVersion: multicloud.platformref.yurikrupnik.com/v1alpha1
#        kind: Sql
##        metadata:
##          name: sql-main-db
##          namespace: crossplane-system
#        spec:
#          location: me-west1
#          compositionSelector:
#            matchLabels:
#              provider: GCP
#    - name: Storage
    - base:
        apiVersion: multicloud.platformref.yurikrupnik.com/v1alpha1
        kind: Storage
        metadata:
          name: project-storage
        spec:
          location: us-west-2
          compositionSelector:
            matchLabels:
              provider: GCP
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.location
#        - fromFieldPath: spec.id
#          toFieldPath: metadata.labels[networks.multicloud.platformref.yurikrupnik.com/network-id]

#    - name: Network
#      base:
#        apiVersion: multicloud.platformref.yurikrupnik.com/v1alpha1
#        kind: Network
#        metadata:
#          name: project-network
#        spec:
#          id: project-network
#          clusterRef:
#            id: multik8s-cluster-gcp
#          compositionSelector:
#            matchLabels:
#              provider: GCP
