apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-users-grpc
  labels:
    app: node-users-grpc
spec:
  replicas: 1
  template:
    metadata:
      name: node-users-grpc
      labels:
        app: node-users-grpc
    spec:
      serviceAccountName: node-users-grpc
      restartPolicy: Always
      containers:
        - name: node-users-grpc
          image: yurikrupnik/node-users-grpc:main
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  key: mongo-uri
                  name: mongo-uri
#            - name: GRPC_TRACE
#              value: "all"
#            - name: GRPC_VERBOSITY
#              value: "DEBUG"
#            - name: GRPC_HOST
#              value: "0.0.0.0:8080"
#              value: "127.0.0.1"
#              value: "0.0.0.0"

          volumeMounts:
            - mountPath: /app/assets
              name: proto-configs
      volumes:
        - name: proto-configs
          configMap:
            name: proto-configs
            items:
              - key: users.proto
                path: users.proto
  selector:
    matchLabels:
      app: node-users-grpc
