apiVersion: v1
kind: Service
metadata:
  name: node-users-grpc-service
  labels:
    run: node-users-grpc-service
spec:
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: 50051
#  ports:
#    - name: http
#      protocol: TCP
#      port: 50051
#      targetPort: 50051
  selector:
    app: node-users-grpc
