version: 2.1
orbs:
  nx: nrwl/nx@1.5.1
jobs:
  main:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            sudo ln -s ../lib/node_modules/corepack/dist/pnpm.js /usr/local/bin/pnpm
            corepack enable
            corepack prepare pnpm@latest-8 --activate
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
#      - run: pnpm ci
      - nx/set-shas

#      - run: npx nx format:check
      - run: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD -t docker-rust --parallel=3
workflows:
  build:
    jobs:
      - main