version: 2.1
orbs:
  nx: nrwl/nx@1.5.1
  pnpm-release-management: rkesters/pnpm-release-management@0.0.1
jobs:
  agent:
    docker:
      - image: cimg/node:lts-browsers
    parameters:
      ordinal:
        type: integer
    steps:
      - checkout
      - run: pnpm i
      - run:
          command: npx nx-cloud start-agent
          no_output_timeout: 60m
  main:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: pnpm i
          cache-path: ~/.pnpm-store
      - nx/set-shas
      - run: npx nx-cloud start-ci-run --stop-agents-after="build"

      - run: npx nx-cloud record -- npx nx format:check
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD -t lint --parallel=3 & npx nx affected --base=$NX_BASE --head=$NX_HEAD -t test --parallel=3 --configuration=ci & npx nx affected --base=$NX_BASE --head=$NX_HEAD -t build --parallel=3
workflows:
  build:
    jobs:
      - agent:
          matrix:
            parameters:
              ordinal: [1, 2, 3]
      - main
