version: 2.1
orbs:
  nx: nrwl/nx@1.5.1
  pnpm-release-management: rkesters/pnpm-release-management@0.0.1
jobs:
  main:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run: pnpm i
      - nx/set-shas
      - run: npx nx format:check
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD -t lint --parallel=3
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD -t test --parallel=3 --configuration=ci
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD -t build --parallel=3
workflows:
  build:
    jobs:
      - main
