#apiVersion: source.toolkit.fluxcd.io/v1
#kind: GitRepository
#metadata:
#  name: go-commands
#  namespace: default
#spec:
#  interval: 30s
#  ref:
#    branch: master
#  url: https://github.com/yurikrupnik/go-commands
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mussia33
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/yurikrupnik/mussia33
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: default
---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: podinfo
#  namespace: flux-system
#spec:
#  interval: 5m0s
#  path: ./k8s/base
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: mussia33
#  targetNamespace: default
