# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  install:
    cmds:
      - helm install -n flux-system flux oci://ghcr.io/fluxcd-community/charts/flux2 --create-namespace
  apply:
    dir: platform/gitops/fluxcd
    cmds:
      - ls
      - kubectl apply -f apps.yaml
  delete:
    dir: platform/gitops/fluxcd
    cmds:
      - kubectl delete -f apps.yaml
