# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  apply:
    dir: platform/gitops/fluxcd
    cmds:
      - ls
      - kubectl apply -f apps.yaml
  delete:
    dir: platform/gitops/fluxcd
    cmds:
      - kubectl delete -f apps.yaml