version: '3'
vars:
  CLUSTER_TYPE: minikube
  INGRESS_TYPE: ingress
tasks:
  kind-local-cluster:up:
    desc: Create kind 4 cores local cluster.
    summary: Create Kind Cluster
    aliases:
      - create
    dir: platform/cluster
    preconditions:
      - echo default CLUSTER_TYPE: {{.CLUSTER_TYPE}}
      - ctlptl create cluster -h
    cmds:
      - ctlptl create cluster {{.CLUSTER_TYPE}} --registry=ctlptl-registry
#      - kind create cluster --config cluster.yaml
      - task: istio
      - echo create cluster {{.CLUSTER_TYPE}}
  kind-local-cluster:down:
    desc: Delete Kind Cluster.
    summary: Delete Kind Cluster.
    aliases:
      - delete
    cmds:
      - ctlptl delete cluster {{.CLUSTER_TYPE}}

  ingress:
    cmds:
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
      - kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=90s

# TODO finish testing
  apigateway:
    cmds:
      - kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.7.1/standard-install.yaml

  istio:
    cmds:
      - up uxp install

  linkerd:
    cmds:
      - echo
