# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  install:
    cmds:
      - vela install -y
      - vela addon enable ~/.vela/addons/velaux
#      - vela port-forward addon-velaux -n vela-system 8080:80
  apply:
    dir: platform/kubevela
    cmds:
      - kubectl apply -f vela.yaml
