apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx-service
spec:
  components:
    - name: nginx-server
      type: webservice
      properties:
        image: yurikrupnik/frontend-solid-apps
        ports:
          - port: 80
            expose: true
      traits:
        - type: autoscaler
          properties:
            min: 3
        - type: ingress
          properties:
            domain: localhost
            http:
              "/": 80
    - name: api-server
      type: webservice
      properties:
        image: yurikrupnik/actix-app:main
        ports:
          - port: 8080
            expose: true
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: yurikrupnik/solid-app:main
        ports:
         - port: 80
           expose: true
    - name: express-server
      type: webservice
      properties:
        image: yurikrupnik/astro:main
        ports:
          - port: 80
            expose: true
#      traits:
#        - type: scaler
#          properties:
#            replicas: 1
#        - type: ingress
#          properties:
#            domain: localhost
#            http:
#              "/": 8080
  policies:
    - name: target-default
      type: topology
      properties:
        clusters: ["local"]
        namespace: "default"
    - name: target-prod
      type: topology
      properties:
        clusters: ["local"]
        namespace: "prod"
    - name: deploy-ha
      type: override
      properties:
        components:
          - type: webservice
            traits:
              - type: scaler
                properties:
                  replicas: 2
  workflow:
    steps:
      - name: deploy2default
        type: deploy
        properties:
          policies: ["target-default"]
      - name: manual-approval
        type: suspend
      - name: deploy2prod
        type: deploy
        properties:
          policies: ["target-prod", "deploy-ha"]
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: go-commands
spec:
  components:
    - name: go-commands
      type: cron-task
      properties:
        image: yurikrupnik/go-commands:v0.0.14
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: clapper
spec:
  components:
    - name: clapper
      type: task # task, raw, k8s-objects
      properties:
        image: yurikrupnik/clapper
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: tier-app
spec:
  components:
    - name: fiber-mongo
      type: webservice
      properties:
        image: yurikrupnik/nest-app:main
        ports:
          - port: 8080
            expose: true
      traits:
        - type: scaler
          properties:
            replicas: 1
        - type: ingress
          properties:
            domain: localhost
            http:
              "/": 80
#    - name: nest-app
#      type: webservice
#      properties:
#        image: yurikrupnik/nest-app
#        ports:
#          - port: 8080
#            expose: true
#      traits:
#        - type: scaler
#          properties:
#            replicas: 1
#        - type: ingress
#          properties:
#            domain: localhost
#            http:
#              "/": 80
#  policies:
#    - name: target-default
#      type: topology
#      properties:
#        clusters: ["local"]
#        namespace: "default"
#    - name: target-prod
#      type: topology
#      properties:
#        clusters: ["local"]
#        namespace: "prod"
#    - name: deploy-ha
#      type: override
#      properties:
#        components:
#          - type: webservice
#            traits:
#              - type: scaler
#                properties:
#                  replicas: 1
#  workflow:
#    steps:
#      - name: deploy2default
#        type: deploy
#        properties:
#          policies: ["target-default"]
#      - name: manual-approval
#        type: suspend
#      - name: deploy2prod
#        type: deploy
#        properties:
#          policies: ["target-prod", "deploy-ha"]
#apiVersion: core.oam.dev/v1beta1
#kind: Application
#metadata:
#  name: docker-fiber-app
#spec:
#  components:
#    - name: express-server
#      type: webservice
#      properties:
#        image: yurikrupnik/docker-fiber-app
#        ports:
#         - port: 8080
#           expose: true
#      traits:
#        - type: scaler
#          properties:
#            replicas: 1
#        - type: ingress
#          properties:
#            domain: localhost
#            http:
#              "/": 80
#  policies:
#    - name: target-default
#      type: topology
#      properties:
#        clusters: ["local"]
#        namespace: "default"
#    - name: target-prod
#      type: topology
#      properties:
#        clusters: ["local"]
#        namespace: "prod"
#    - name: deploy-ha
#      type: override
#      properties:
#        components:
#          - type: webservice
#            traits:
#              - type: scaler
#                properties:
#                  replicas: 2
#  workflow:
#    steps:
#      - name: deploy2default
#        type: deploy
#        properties:
#          policies: ["target-default"]
#      - name: manual-approval
#        type: suspend
#      - name: deploy2prod
#        type: deploy
#        properties:
#          policies: ["target-prod", "deploy-ha"]
