apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-api
  labels:
    app: mongo-api
spec:
  replicas: 1
  template:
    metadata:
      name: mongo-api
      labels:
        app: mongo-api
    spec:
      serviceAccountName: mongo-api
      restartPolicy: Always
      containers:
        - name: mongo-api
          image: yurikrupnik/mongo-api:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
#          env:
#            - name: MONGO_URI
#              valueFrom:
#                secretKeyRef:
#                  key: mongo-uri
#                  name: mongo-uri
  selector:
    matchLabels:
      app: mongo-api
