apiVersion: v1
kind: Service
metadata:
  name: mongo-api
  annotations:
    "prometheus.io/scrape": "true"
  labels:
    run: mongo-api
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: mongo-api
