apiVersion: v1
kind: Service
metadata:
  name: frontend-solid-app-service
  labels:
    run: frontend-solid-app-service
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: frontend-solid-app
