# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  init-module:
    cmds:
      - cue mod init github.com/yurikrupnik/github-actions-example
  import:
#    dir: platform/cue
    cmds:
      - cue import configMap.yml
      - cue import -l '#Workflow:' -p github jsonschema: https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
