#apiVersion: storage.gcp.upbound.io/v1beta1
#kind: Bucket
#metadata:
#  name: example
#  labels:
#    project: mussia30
#  annotations:
#    crossplane.io/external-name: upbound-bucket-a3aa0af89
#spec:
#  forProvider:
#    location: US
#    storageClass: MULTI_REGIONAL
#  providerConfigRef:
#    name: default
#  deletionPolicy: Delete
---
apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
#  generateName: crossplane-bucket-
  name: yuri-crossplane-bucket
  labels:
    docs.crossplane.io/example: provider-gcp
spec:
  forProvider:
    location: US
    storageClass: MULTI_REGIONAL
  providerConfigRef:
    name: default
  deletionPolicy: Delete
---
apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-bucket-mussia30
  labels:
    docs.crossplane.io/example: provider-gcp
  annotations:
    crossplane.io/external-name: mussia30-temp-bucket
spec:
  forProvider:
    location: US
    storageClass: MULTI_REGIONAL
    labels:
      arios: sadsd
      team: backend
  providerConfigRef:
    name: default
  deletionPolicy: Delete
---
apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-bucket-alina
  labels:
    docs.crossplane.io/example: provider-gcp
  annotations:
    crossplane.io/external-name: alina-temp-bucket
spec:
  forProvider:
    location: US
    storageClass: MULTI_REGIONAL
    labels:
      app: alina
      team: yuri
  providerConfigRef:
    name: default
  deletionPolicy: Delete
---
#apiVersion: s3.aws.upbound.io/v1beta1
#kind: Bucket
#metadata:
#  annotations:
#    crossplane.io/external-name: test-channel-bucket
#    meta.upbound.io/example-id: configservice/v1beta1/awsconfigurationrecorderstatus
#  labels:
#    testing.upbound.io/example-name: b
#  name: test-channel-bucket-yuri
#spec:
#  forProvider:
#    forceDestroy: true
#    region: us-west-1
#---
#apiVersion: s3.aws.upbound.io/v1beta1
#kind: Bucket
#metadata:
#  annotations:
#    crossplane.io/external-name: yuri-north-bucket
#    meta.upbound.io/example-id: configservice/v1beta1/awsconfigurationrecorderstatus
#  labels:
#    testing.upbound.io/example-name: b
#  name: yuri-north-bucket
#spec:
#  forProvider:
#    forceDestroy: true
#    region: eu-west-3
