apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: compositebucket.example.com
spec:
  group: example.com
  names:
    kind: CompositeBucket
    plural: compositebuckets
    singular: compositebucket
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
#apiVersion: example.com/v1alpha1
#kind: ParamBucket
#metadata:
#  name: my-param-bucket
#spec:
#  provider: "gcp"
#  bucketName: "my-bucket-yurik"
#  region: "us-west1"
#  params:
#    - name: provider
#      required: true
#      default: "gcp"
#      enum:
#        - "gcp"
#        - "aws"
#    - name: bucketName
#      required: true
#    - name: region
#      required: false
#      default: "us-west1"
#---
#apiVersion: apiextensions.k8s.io/v1
#kind: CustomResourceDefinition
#metadata:
#  name: parameters.example.com
#spec:
#  group: example.com
#  names:
#    kind: Parameter
#    listKind: ParameterList
#    plural: parameters
#    singular: parameter
#  scope: Cluster
#  versions:
#    - name: v1
#      served: true
#      storage: true
#---
#apiVersion: example.com/v1
#kind: Parameter
#metadata:
#  name: my-param-bucket
#spec:
#  parameters:
#    - name: provider
#      value: "aws"
#    - name: bucketName
#      value: "my-bucket-aws"
#    - name: region
#      value: "us-west-2"
