apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: Topic
metadata:
  name: crossplane-topic-mussia30
  labels:
    docs.crossplane.io/example: provider-gcp
  annotations:
    crossplane.io/external-name: mussia30-temp-topic
spec:
  forProvider:
    schemaSettings:
      - encoding: JSON
        schema: "schema"
  providerConfigRef:
    name: default
  deletionPolicy: Delete
---
apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: eventarc/v1beta1/trigger
  labels:
    testing.upbound.io/example-name: trigger
  name: trigger
spec:
  forProvider: {}
---
apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: Schema
metadata:
  annotations:
    meta.upbound.io/example-id: pubsub/v1beta1/schema
  labels:
    testing.upbound.io/example-name: schema
  name: schema
spec:
  forProvider:
    definition: |
      {
        "type" : "record",
        "name" : "Avro",
        "fields" : [
          {
            "name" : "StringField",
            "type" : "string"
          },
          {
            "name" : "IntField",
            "type" : "int"
          }
        ]
      }
    type: AVRO
