# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  local:
    cmds:
      - task: cluster
      - task: install
      - task: create-secret
      - task: create-gcp-provider
      - tilt up
  cluster:
    cmds:
      - minikube start
      - minikube addons enable gcp-auth
  install:
    dir: platform/crossplane
    cmds:
      - helm repo add crossplane-stable https://charts.crossplane.io/stable && helm repo update
      - helm install crossplane --namespace crossplane-system --create-namespace crossplane-stable/crossplane
      - kubectl -n crossplane-system wait deployment crossplane --for=condition=Available --timeout=180s
      - kubectl get pods -n crossplane-system
      - kubectl get deployments -n crossplane-system
  create-secret:
    cmds:
      - kubectl create secret generic aws-secret -n crossplane-system --from-file=creds=./aws_creds.txt
#      - kubectl create secret generic gcp-secret -n crossplane-system --from-file=creds=./gcp-credentials.json
  create-gcp-provider:
    dir: platform/crossplane
    cmds:
      - kubectl apply -f gcpProvider.yaml
      - kubectl wait "providers.pkg.crossplane.io/provider-gcp" --for=condition=Installed --timeout=300s
      - kubectl wait "providers.pkg.crossplane.io/provider-gcp" --for=condition=Healthy --timeout=300s
      - kubectl wait "providers.pkg.crossplane.io/provider-aws" --for=condition=Installed --timeout=300s
      - kubectl wait "providers.pkg.crossplane.io/provider-aws" --for=condition=Healthy --timeout=300s
      - kubectl get providers
      - kubectl apply -f gcpProviderConfig.yaml
  create-resources:
    dir: platform/crossplane
    cmds:
      - kubectl apply -f gcpBucket.yaml
      - kubectl apply -f gcpTopic.yaml
      - kubectl apply -f advanced.yaml
# Compositions
      - kubectl apply -f composition.yaml
      - kubectl apply -f compositeResourceDefinition.yaml
  get-buckets:
    cmds:
      - kubectl get managed
      - kubectl get xrd
      - kubectl get composite
      - kubectl get composition
      - kubectl get bucket
      - kubectl get buckets yuri-crossplane-bucket -o jsonpath='{.status.atProvider.url}'
      - kubectl get buckets.storage.gcp.upbound.io yuri-crossplane-bucket
  delete-schemas:
    cmds:
      - kubectl delete schema --selector testing.upbound.io/example-name=trigger
  delete-bucket:
    cmds:
      - kubectl delete bucket --selector docs.crossplane.io/example=provider-gcp
  delete-schema:
    cmds:
      - kubectl delete schema --selector testing.upbound.io/example-name=schema
  get-xrd:
    cmds:
      - kubectl get TopicBucket -n test
      - kubectl get topicbucket -A
      - kubectl get xtopicbucket
      - kubectl get xrd
      - kubectl get composite
      - kubectl get composition
      - kubectl get xdatasetwithbucket
  delete-composite:
    cmds:
      - kubectl delete XTopicBucket my-second-composite-resource
      - kubectl delete xtopicbucket my-composite-resource
  delete-claim:
    cmds:
      - kubectl delete topicbucket claimed-topic-with-bucket -n test
      - kubectl delete topicbucket second-claimed-topic-with-bucket -n test2

