apiVersion: batch/v1
kind: CronJob
metadata:
  name: clapper-cron-job
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: clapper
              image: yurikrupnik/clapper:main
              imagePullPolicy: IfNotPresent
              command:
                - /app
                - --name
                - aris
          restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
    - name: command-demo-container
      image: yurikrupnik/clapper
      args: ["--name", "Nir"]
  restartPolicy: OnFailure
