
local_resource(
  'build-node-users-redis',
  dir="../../..",
  cmd='pnpm nx run node-node-users-redis:build',
  deps=['.', '../../../libs/node'],
  resource_deps=["pnpm"],
  ignore=["k8s"],
  env={"GOOS":"linux","GOARCH":"amd64"},
  labels=["pnpm"],
)

docker_build(
  "yurikrupnik/node-users-redis",
  "../../..",
  target="node",
  build_args={"DIST_PATH":"dist/apps/node/node-users-redis"},
  only=["dist/apps/node/node-users-redis"],
)
