# permissions for end users to view containerinjectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: containerinjector-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: containerinjector-viewer-role
rules:
- apiGroups:
  - storage.dev.yurikrupnik
  resources:
  - containerinjectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.dev.yurikrupnik
  resources:
  - containerinjectors/status
  verbs:
  - get
