docker_build(
  "yurikrupnik/mongo-api",
  "../../..",
  dockerfile="../../../Dockerfile.rust",
  build_args={"APP_NAME":"mongo_api"},
  target="rust",
)

# k8s_yaml(kustomize('k8s/base'))

k8s_resource("mongo-api", port_forwards="5211:8080")