docker_build(
  "yurikrupnik/mongo-api",
  "../../..",
  dockerfile="../../../Dockerfile.rust",
  build_args={"APP_NAME":"mongo_api"},
  target="rust",
  only=[
      "Cargo.toml",
      "Cargo.lock",
      "nx.json",
      "libs/rust/",
      "apps/rust/",
      "apps/rust/mongo-api/src",
    ],
)


k8s_resource("mongo-api", port_forwards="5411:8080")
