apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-nest-app
#  namespace: mussia30
  labels:
    app: node-nest-app
    version: v1
spec:
  replicas: 1

  template:
    metadata:
      name: node-nest-app
      labels:
        app: node-nest-app
        version: v1
      annotations:
        "linkerd.io/inject": "enabled"
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service": "node-nest-app"
        "consul.hashicorp.com/connect-service-protocol": "http"
        "consul.hashicorp.com/service-meta-version": "v.1.1"
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "9102"
    spec:
      serviceAccountName: node-nest-app
      restartPolicy: Always
      containers:
        - name: node-nest-app
          image: yurikrupnik/node-nest-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: GRPC_TRACE
              value: "all"
            - name: GRPC_VERBOSITY
              value: "DEBUG"
            - name: MONGO_URI
              value: "mongodb://host.docker.internal"
            - name: REDIS_HOST
              value: "host.docker.internal"
            - name: GRPC_HOST
#              value: "http://127.0.0.1:2379"
#              value: "0.0.0.0"
              value: "node-users-grpc-service:50051"
#            - name: PORT
#              value: "5000"
#              value: "127.0.0.1:8080"
#            - name: REDIS_PORT
#            - name: REDIS_PASSWORD
          ports:
            - name: liveness-port
              containerPort: 8080
              hostPort: 8080
            - name: grpc
              containerPort: 50051
            ## Used to detect when an application degrades to broken states and
            ## cannot recover except by being restarted.
            ##
            ## https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command
          livenessProbe:
            httpGet:
#              port: liveness-port
              port: 8080
              path: /api/health
#            grpc:
#              port: 8080
            failureThreshold: 1
            periodSeconds: 10

            ## Used to detect when an application is no longer able to service traffic.
            ## https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes
#            readinessProbe:
#              exec:
#                command: [ "/usr/bin/grpc_health_probe", "-addr=:8080" ]
#              initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /app/assets
              name: proto-configs
      volumes:
        - name: proto-configs
          configMap:
            name: proto-configs
            items:
              - key: users.proto
                path: users.proto
  selector:
    matchLabels:
      app: node-nest-app
      version: v1
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: etcd-with-grpc
#spec:
#  containers:
#    - name: etcd
#      image: registry.k8s.io/etcd:3.5.1-0
#      command: [ "/usr/local/bin/etcd", "--data-dir",  "/var/lib/etcd", "--listen-client-urls", "http://0.0.0.0:2379", "--advertise-client-urls", "http://127.0.0.1:2379", "--log-level", "debug"]
#      ports:
#        - containerPort: 2379
#      livenessProbe:
#        grpc:
#          port: 2379
#        initialDelaySeconds: 10
