apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-nest-app
#  namespace: mussia30
  labels:
    app: node-nest-app
    version: v1
spec:
  replicas: 1

  template:
    metadata:
      name: node-nest-app
      labels:
        app: node-nest-app
        version: v1
      annotations:
        "linkerd.io/inject": "enabled"
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service": "node-nest-app"
        "consul.hashicorp.com/connect-service-protocol": "http"
        "consul.hashicorp.com/service-meta-version": "v.1.1"
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "9102"
    spec:
      serviceAccountName: node-nest-app
      restartPolicy: Always
      containers:
        - name: node-nest-app
          image: yurikrupnik/node-nest-app:latest
          imagePullPolicy: IfNotPresent
          env:
#            - name: GRPC_TRACE
#              value: "all"
#            - name: GRPC_VERBOSITY
#              value: "DEBUG"
            - name: MONGO_URI
              value: "mongodb://host.docker.internal"
            - name: REDIS_HOST
              value: "host.docker.internal"
            - name: GRPC_HOST
#              value: "0.0.0.0:8080"
              value: "127.0.0.1:5000"
#            - name: PORT
#              value: "5000"
#              value: "127.0.0.1:8080"
#            - name: REDIS_PORT
#            - name: REDIS_PASSWORD
          volumeMounts:
            - mountPath: /app/assets
              name: proto-configs
      volumes:
        - name: proto-configs
          configMap:
            name: proto-configs
            items:
              - key: users.proto
                path: users.proto
  selector:
    matchLabels:
      app: node-nest-app
      version: v1
