apiVersion: v1
kind: Service
metadata:
  name: node-nest-app
  labels:
    run: node-nest-app
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: node-nest-app
