# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  up:
    dir: platform/app/compose
    cmds:
      - docker-compose up -d
  down:
    dir: platform/app/compose
    cmds:
      - docker-compose down
