version: "3.9"
services:
  db:
    image: "mongo"
    ports:
      - "27017:27017"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  nest-app:
    build:
      context: ../
      args:
        - DIST_PATH=dist/apps/node/nest-app
        - REDIS_HOST=redis
    container_name: nest-app
    environment:
      - MONGO_URI=mongodb://db/compose
    ports:
      - 8080:8080
#    command: npm run start
    depends_on:
      - db
