# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  compose:up:
    cmds:
      - docker-compose up -d
    dir: scripts
  compose:down:
    cmds:
      - docker-compose down
    dir: scripts
  gcloud-set:
    cmds:
      - gcloud config list
