
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Production project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.3.2
    helm:
      releaseName: redis
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cache
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io/
    targetRevision: 0.8.3
    helm:
      releaseName: external-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 52.1.0
    helm:
      releaseName: kube-prometheus-stack
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-prometheus-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: prometheus
#  namespace: argocd
#spec:
#  project: default
#  source:
#    chart: prometheus
#    repoURL: https://prometheus-community.github.io/helm-charts
#    targetRevision: 21.1.2
#    helm:
#      releaseName: prometheus
#  destination:
#    server: "https://kubernetes.default.svc"
#    namespace: prometheus
#  syncPolicy:
#    syncOptions:
#      - CreateNamespace=true
#    automated:
#      selfHeal: true
#      prune: true
#      allowEmpty: true
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
# name: robusta
# namespace: argocd
#spec:
# project: default
# source:
#   chart: robusta
#   repoURL: https://robusta-charts.storage.googleapis.com/
#   targetRevision: 0.10.15
#   helm:
#     releaseName: robusta
# destination:
#   server: "https://kubernetes.default.svc"
#   namespace: robusta
# syncPolicy:
#   automated:
#     selfHeal: true
#     prune: true
#     allowEmpty: true
#   syncOptions:
#     - CreateNamespace=true
#syncPolicy:
#   syncOptions:
#       - CreateNamespace=true
#   automated:
#     selfHeal: true
#     prune: true
#     allowEmpty: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-rollouts
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.32.2
    helm:
      releaseName: argo-rollouts
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-rollouts
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: myapp-argo-application
 namespace: argocd
spec:
 project: default
 source:
   repoURL: https://github.com/yurikrupnik/nx-go-playground.git
   targetRevision: HEAD
   path: k8s/base
 destination:
   server: https://kubernetes.default.svc
   namespace: nx-go-playground

 syncPolicy:
   syncOptions:
     - CreateNamespace=true

   automated:
     selfHeal: true
     prune: true
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#  name: mussia30
#  namespace: argocd
# spec:
#  project: default
#  source:
#    repoURL: https://github.com/yurikrupnik/mussia30.git
#    targetRevision: HEAD
#    path: k8s/base
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: mussia30

#  syncPolicy:
#    syncOptions:
#      - CreateNamespace=true

#    automated:
#      selfHeal: true
#      prune: true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: fiber-mongo-application
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/yurikrupnik/fiber-mongo.git
#     targetRevision: HEAD
#     path: k8s/base
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: fiber-mongo

#   syncPolicy:
#     syncOptions:
#       - CreateNamespace=true

#     automated:
#       selfHeal: true
#       prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: go-commands
 namespace: argocd
spec:
 project: default
 source:
   repoURL: https://github.com/yurikrupnik/go-commands.git
   targetRevision: HEAD
   path: k8s/base
 destination:
   server: https://kubernetes.default.svc
   namespace: go-commands

 syncPolicy:
   syncOptions:
     - CreateNamespace=true

   automated:
     selfHeal: true
     prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mussia33
  namespace: argocd
#  labels:
#    argocd.argoproj.io/instance: argocd
#    argocd.argoproj.io/managed-by: argocd-server
#    argocd.argoproj.io/secret-type: repository
#    argocd.argoproj.io/private-repo: "false"
#    argocd.argoproj.io/repo:
spec:
  project: default
  source:
    repoURL: https://github.com/yurikrupnik/mussia33.git
    targetRevision: HEAD
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: mussia33
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mussia34
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: argocd
    argocd.argoproj.io/managed-by: argocd-server
    argocd.argoproj.io/secret-type: repository
    argocd.argoproj.io/private-repo: "true"
#    argocd.argoproj.io/repo:
spec:
  project: default
  source:
    repoURL: https://github.com/yurikrupnik/mussia34.git
    targetRevision: HEAD
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: mussia34
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: rust-playground
#  namespace: rust-playground
#spec:
#  project: default
#  source:
#    repoURL: https://github.com/yurikrupnik/rust-playground.git
#    targetRevision: HEAD
#    path: k8s/base
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: rust-playground
#
#  syncPolicy:
#    syncOptions:
#      - CreateNamespace=true
#
#    automated:
#      selfHeal: true
#      prune: true
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: crossplane
#  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
#spec:
#  project: default
#  source:
#    chart: crossplane
#    repoURL: https://charts.crossplane.io/stable
#    targetRevision: "1.11.3"
#  destination:
#    namespace: crossplane-system
#    server: https://kubernetes.default.svc
#  syncPolicy:
#    automated:
#      selfHeal: true
#      prune: true
#      allowEmpty: true
#    syncOptions:
#      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: kubevela
 namespace: argocd
 finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
 project: default
 source:
   chart: vela-core
   repoURL: https://charts.kubevela.net/core
   targetRevision: "1.8.1"
 destination:
   namespace: vela-system
   server: https://kubernetes.default.svc
 syncPolicy:
   automated:
     selfHeal: true
     prune: true
     allowEmpty: true
   syncOptions:
     - CreateNamespace=true
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: istio-base
#  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
#spec:
#  project: default
#  source:
#    chart: base
#    repoURL: https://istio-release.storage.googleapis.com/charts
#    targetRevision: "1.17.2"
#  destination:
#    namespace: istio-system
#    server: https://kubernetes.default.svc
#  syncPolicy:
#    automated:
#      selfHeal: true
#      prune: true
#      allowEmpty: true
#    syncOptions:
#      - CreateNamespace=true
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: istiod
#  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
#spec:
#  project: default
#  source:
#    chart: istiod
#    repoURL: https://istio-release.storage.googleapis.com/charts
#    targetRevision: "1.17.2"
#  destination:
#    namespace: istio-system
#    server: https://kubernetes.default.svc
#  syncPolicy:
#    automated:
#      selfHeal: true
#      prune: true
#      allowEmpty: true
#    syncOptions:
#      - CreateNamespace=true
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: gateway
#  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
#spec:
#  project: default
#  source:
#    chart: gateway
#    repoURL: https://istio-release.storage.googleapis.com/charts
#    targetRevision: "1.17.2"
#  destination:
#    namespace: istio-ingress
#    server: https://kubernetes.default.svc
#  syncPolicy:
#    automated:
#      selfHeal: true
#      prune: true
#      allowEmpty: true
#    syncOptions:
#      - CreateNamespace=true
#---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#  name: nginx
#  namespace: argocd
# spec:
#  project: default
#  source:
#    chart: nginx-ingress
#    repoURL: https://helm.nginx.com/stable
#    targetRevision: 1.16.1
#    helm:
#      releaseName: nginx
#  destination:
#    server: "https://kubernetes.default.svc"
#    namespace: nginx
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: guestbook-helm
# spec:
#   project: default
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: guestbook-helm
#   source:
#     repoURL: https://github.com/argoproj/argocd-example-apps.git
#     targetRevision: HEAD
#     path: helm-guestbook

#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: guestbook-kustomize
#spec:
#  project: default
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: guestbook-kustomize
#  sources:
##    - chart: elasticsearch
##      repoURL: https://helm.elastic.co
##      targetRevision: 8.5.1
##        - repoURL: https://github.com/argoproj/argocd-example-apps.git
##          path: guestbook
##          targetRevision: HEAD
#    - repoURL: 'https://prometheus-community.github.io/helm-charts'
#      chart: prometheus
#      targetRevision: 15.7.1
#      helm:
#        valueFiles:
#          - $values/charts/prometheus/values.yaml
#    - repoURL: 'https://github.com/yurikrupnik/go-commands.git'
#      targetRevision: HEAD
#      path:
#    - repoURL: 'https://git.example.gom/org/value-files.git'
#      targetRevision: HEAD
#      ref: values
#    - repoURL: https://github.com/argoproj/argocd-example-apps.git
#      path: guestbook
#      targetRevision: HEAD
#    - chart: elasticsearch
#      repoURL: https://helm.elastic.co
#      targetRevision: 8.5.1
#  source:
##    -
#    - repoURL: 'https://prometheus-community.github.io/helm-charts'
#      chart: prometheus
#      targetRevision: 15.7.1
#      helm:
#        valueFiles:
#          - $values/charts/prometheus/values.yaml
##    -
#  - repoURL: https://github.com/argoproj/argocd-example-apps.git
#    targetRevision: HEAD
#    path: kustomize-guestbook

#    kustomize:
#      version: v3.5.4
