apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aws.compositestorages.multicloud.platformref.yurikrupnik.com
  labels:
    provider: AWS
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: multicloud.platformref.yurikrupnik.com/v1alpha1
    kind: CompositeStorage
  resources:
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        metadata:
          name: yuriks-bucket-via-crossplane-aws
        spec:
          forProvider:
            region: eu-west-1
          reclaimPolicy: Delete
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: spec.providerConfigRef
          toFieldPath: spec.providerConfigRef
        - fromFieldPath: spec.location
          toFieldPath: spec.forProvider.region

