apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositestorages.multicloud.platformref.yurikrupnik.com
spec:
  claimNames:
    kind: Storage
    plural: storages
  group: multicloud.platformref.yurikrupnik.com
  #           todo test it!
#  connectionSecretKeys:
#    - kubeconfig
#    - value
  defaultCompositionRef:
    name: gcp.compositestorages.multicloud.platformref.yurikrupnik.com
  names:
    kind: CompositeStorage
    plural: compositestorages
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                providerConfigRef:
                  type: object
                  description: "A reference to the ProviderConfig object that this registry will be used for."
                  properties:
                    name:
                      type: string
                      description: Name of the ProviderConfig object this ref points to.
                  required:
                    - name
                id:
                  type: string
                  description: Id of the bucket that should be created.
                location:
                  type: string
                  description: Location where the bucket should be created.
                storageClass:
                  type: string
                  description: Storage Class of the bucket.
                  default: STANDARD
                  enum:
                    - STANDARD
                    - MULTI_REGIONAL
                    - REGIONAL
                    - NEARLINE
                    - COLDLINE
                    - ARCHIVE
#                labels:
#                  type: array
#                  description: Labels to apply to the bucket.
#                  items:
#                    type: object
#                    properties:
#                      key:
#                        type: string
#                        description: Label key.
#                      value:
#                        type: string
#                        description: Label value.
              required:
                - id
                - location

            status:
              type: object
              properties:
                url:
                  type: string
