# https://taskfile.dev

version: '3'
#includes:
#  compose: ./compose
#  cluster: ./platform/cluster
vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
