apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: crossplane-ui
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: komoplane
                port:
                  number: 8090
---
apiVersion: argocd.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: argocd-provider
spec:
  credentials:
    secretRef:
      key: authToken
      name: argocd-credentials
      namespace: crossplane-system
    source: Secret
  insecure: true
  plainText: false
  serverAddr: argocd-server.argocd.svc:443
---
apiVersion: applications.argocd.crossplane.io/v1alpha1
kind: Application
metadata:
  name: example-application
spec:
  forProvider:
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    project: default
    source:
      path: charts/podinfo
      repoURL: https://github.com/stefanprodan/podinfo/
      targetRevision: HEAD
  providerConfigRef:
    name: argocd-provider
---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: wordpress-example-patched
spec:
  forProvider:
    chart:
      name: wordpress
      repository: https://charts.bitnami.com/bitnami
      version: 15.2.5
    namespace: wordpress
#    patchesFrom:
#      - configMapKeyRef:
#          key: patch.yaml
#          name: wp-patch
#          namespace: wordpress
#          optional: false
#    set:
#      - name: param1
#        value: value2
#    values:
#      param1: value1
#      param2: 1
  providerRef:
    name: crossplane-provider-helm
---
apiVersion: multicloud.platformref.yurikrupnik.com/v1alpha1
kind: Storage
metadata:
  name: storage-aws
spec:
  location: us-west-2
  compositionSelector:
    matchLabels:
      provider: AWS
---
apiVersion: multicloud.platformref.yurikrupnik.com/v1alpha1
kind: Storage
metadata:
  name: storage-gcp
spec:
  location: us-west1
  compositionSelector:
    matchLabels:
      provider: GCP
---
apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/notification
  labels:
    testing.upbound.io/example-name: project-usage-tracking-bucket-11
  name: project-usage-tracking-bucket-11
spec:
  forProvider:
    location: US
