# https://taskfile.dev

version: '3'

vars:
  #    ACCOUNT: krupnik.yuri@gmail.com
  #    PROJECT: shared-404221
  PROJECT: devops-386509
  ACCOUNT: yurik@sela.co.il
  BUILDER_ACCOUNT: container-builder@sdp-demo-388112.iam.gserviceaccount.com
  BUILDER_PROJECT: shared-404221
#  BUILDER_PROJECT: personal-to-yuri
#  BUILDER_PROJECT: sdp-demo-388112

tasks:
  set-gcp:
    aliases:
      - config
    summary: |
      Set gcloud account and project
    silent: true
    desc: |
      Set gcloud account and project
    cmds:
      - gcloud config set account {{.ACCOUNT}}
      - gcloud config set project {{.PROJECT}}
      - gcloud auth list
      - gcloud config list
  get-identity:
    cmds:
      - gcloud auth print-identity-token
  get-access:
    cmds:
      - gcloud auth print-access-token
  get-refresh:
    cmds:
      - gcloud auth activate-service-account {{.ACCOUNT}}
