apiVersion: apps/v1
kind: Deployment
metadata:
  name: surrealdb
spec:
  selector:
    matchLabels:
      app: surrealdb
  template:
    metadata:
      labels:
        app: surrealdb
    spec:
      containers:
        - name: surrealdb
          image: surrealdb/surrealdb:latest
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: surrealdb
spec:
  type: ClusterIP
  selector:
    app: surrealdb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
